'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    isRTL: boolean;
    translateText: (text: string) => Promise<string>;
    isTranslating: boolean;
    translationError: string | null;
    supportedLanguages: { language: string, name: string }[];
    getSupportedLanguages: () => Promise<void>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
    ar: {
        // Common & General UI
        'common.loading': 'جاري التحميل...',
        'common.error': 'حدث خطأ',
        'common.success': 'تم بنجاح',
        'common.cancel': 'إلغاء',
        'common.confirm': 'تأكيد',
        'common.save': 'حفظ',
        'common.edit': 'تعديل',
        'common.delete': 'حذف',
        'common.add': 'إضافة',
        'common.search': 'بحث',
        'common.actions': 'الإجراءات',
        'common.status': 'الحالة',
        'common.date': 'التاريخ',
        'common.yes': 'نعم',
        'common.no': 'لا',

        // Header & Layout
        'header.title': 'رِداء - Ridaa',
        'header.subtitle': 'لوحة تحكم الإدارة',
        'admin.login': 'تسجيل دخول الإدارة',
        'admin.dashboard': 'لوحة التحكم',
        'admin.logout': 'تسجيل خروج',
        'admin.username': 'اسم المستخدم',
        'admin.password': 'كلمة المرور',
        'admin.home': 'الرئيسية',
        'admin.back': 'رجوع',
        'admin.refresh': 'تحديث',
        'admin.refreshData': 'تحديث البيانات',
        'admin.export': 'تصدير',
        'admin.exportSuccess': 'تم تصدير {count} من العناصر بنجاح',
        'admin.import': 'استيراد',

        // Products Management
        'admin.products': 'إدارة المنتجات',
        'admin.manageProducts': 'إدارة وتنظيم منتجات المتجر',
        'admin.addProduct': 'إضافة منتج جديد',
        'admin.addProductDesc': 'ابدأ بإضافة منتج جديد للمتجر',
        'admin.editProduct': 'تعديل المنتج',
        'admin.deleteProduct': 'حذف المنتج',
        'admin.confirmDelete': 'هل أنت متأكد من حذف هذا العنصر؟',
        'admin.totalProducts': 'إجمالي المنتجات',
        'admin.activeProducts': 'المنتجات النشطة',
        'admin.featuredProducts': 'المنتجات المميزة',
        'admin.searchProducts': 'البحث في المنتجات...',
        'admin.active': 'نشط',
        'admin.inactive': 'غير نشط',
        'admin.outOfStock': 'نفد من المخزن',
        'admin.featured': 'مميز',
        'admin.new': 'جديد',
        'admin.bestseller': 'الأكثر مبيعاً',
        'admin.noProducts': 'لا توجد منتجات',
        'admin.saveProduct': 'حفظ المنتج',
        'admin.updateProduct': 'تحديث المنتج',
        'admin.productCreated': 'تم إنشاء المنتج بنجاح',
        'admin.productUpdated': 'تم تحديث المنتج بنجاح',
        'admin.errorCreatingProduct': 'حدث خطأ في إنشاء المنتج',
        'admin.filters': 'المرشحات',
        'admin.allCategories': 'جميع الأقسام',
        'admin.allStatuses': 'جميع الحالات',
        'admin.variants': 'المتغيرات',
        'admin.size': 'المقاس',
        'admin.color': 'اللون',
        'admin.stock': 'المخزون',
        'admin.uploadFile': 'رفع ملف',
        'admin.addURL': 'إضافة رابط',
        'admin.variantsDesc': 'المتغيرات (المقاسات والألوان)',

        'admin.addVariant': 'إضافة متغير',
        'admin.enterImageUrl': 'أدخل رابط الصورة',
        'admin.sessionExpired': 'انتهت صلاحية الجلسة. يرجى تسجيل الدخول مرة أخرى.',
        'admin.fillRequiredFields': 'يرجى ملء كافة الحقول المطلوبة',

        // Product Form Fields
        'admin.productImages': 'صور المنتج',
        'admin.category': 'القسم',
        'admin.selectCategory': 'اختر القسم',
        'admin.basicInformation': 'المعلومات الأساسية',
        'admin.descriptions': 'الأوصاف',
        'admin.pricingInventory': 'التسعير والمخزون',
        'admin.productName': 'اسم المنتج',
        'admin.slug': 'الرابط المختصر',
        'admin.sku': 'رمز المنتج (SKU)',
        'admin.gender': 'الجنس',
        'admin.unisex': 'للجنسين',
        'admin.male': 'رجالي',
        'admin.female': 'نسائي',
        'admin.description': 'الوصف',
        'admin.shortDescription': 'الوصف المختصر',
        'admin.price': 'السعر',
        'admin.salePrice': 'سعر البيع',
        'admin.discountPercent': 'نسبة الخصم',
        'admin.metaTitleEn': 'العنوان لمحركات البحث (إنجليزي)',
        'admin.metaTitleAr': 'العنوان لمحركات البحث (عربي)',
        'admin.metaDescriptionEn': 'الوصف لمحركات البحث (إنجليزي)',
        'admin.metaDescriptionAr': 'الوصف لمحركات البحث (عربي)',
        'admin.shortDescriptionAr': 'الوصف المختصر (عربي)',
        'admin.shortDescriptionEn': 'الوصف المختصر (إنجليزي)',
        'admin.comment': 'التعليق',
        'admin.target': 'الهدف',
        'admin.cancelAction': 'إلغاء',
        'admin.errorLoadingProduct': 'حدث خطأ في تحميل المنتج',
        'admin.errorUpdatingProduct': 'حدث خطأ في تحديث المنتج',
        'admin.productSettings': 'إعدادات المنتج',
        'admin.activeProduct': 'منتج نشط',
        'admin.featuredProduct': 'منتج مميز',

        'admin.categories': 'الأقسام',
        'admin.manageCategories': 'إدارة وتنظيم أقسام المتجر',
        'admin.manageCategoriesDesc': 'إدارة أقسام المنتجات وتصنيفاتها',
        'admin.addCategory': 'إضافة قسم جديد',
        'admin.editCategory': 'تعديل القسم',
        'admin.categoryNotFound': 'القسم غير موجود',
        'admin.errorFetchingCategory': 'حدث خطأ في جلب بيانات القسم',
        'admin.categoryUpdated': 'تم حفظ التغييرات بنجاح',
        'admin.searchCategories': 'البحث في الأقسام...',
        'admin.noCategories': 'لا توجد أقسام حالياً',
        'admin.confirmDeleteCategory': 'هل أنت متأكد من حذف قسم "{name}"؟ سيؤدي هذا لإزالة تصنيف المنتجات المرتبطة به.',
        'admin.categoryDeleted': 'تم حذف قسم "{name}" بنجاح',
        'admin.errorDeletingCategory': 'حدث خطأ أثناء محاولة حذف القسم',
        'admin.saveCategory': 'حفظ القسم',
        'admin.categoryCreated': 'تم إنشاء القسم بنجاح',
        'admin.parentCategory': 'القسم الأب',
        'admin.activeCategory': 'قسم نشط',
        'admin.termsAndPrivacy': 'الشروط والخصوصية',
        'admin.privacyPolicy': 'سياسة الخصوصية',
        'admin.termsAndConditions': 'الشروط والأحكام',
        'admin.editStaticPages': 'إدارة الصفحات الثابتة',
        'admin.basicInfo': 'البيانات الأساسية',
        'admin.media': 'الوسائط والصور',
        'admin.seoAndTags': 'SEO والوسوم',
        'admin.commaSeparated': 'افصل بين الكلمات بفاصلة (,)',
        'admin.saveSuccess': 'تم الحفظ بنجاح',
        'admin.saveError': 'حدث خطأ أثناء الحفظ',

        // Orders Management
        'admin.orders': 'الطلبات',
        'admin.manageOrders': 'إدارة ومتابعة طلبات العملاء',
        'admin.manageOrdersDesc': 'إدارة ومتابعة طلبات العملاء بكفاءة',
        'admin.searchOrders': 'البحث في الطلبات...',
        'admin.totalOrders': 'إجمالي الطلبات',
        'admin.pending': 'تم إنشاء الطلب',
        'admin.confirmed': 'جاري التجهيز',
        'admin.shipped': 'تم الشحن',
        'admin.outForDelivery': 'خرج للتوصيل',
        'admin.delivered': 'تم التوصيل',
        'admin.cancelled': 'ملغي',
        'admin.order': 'الطلب',
        'admin.customer': 'العميل',
        'admin.status': 'الحالة',
        'admin.date': 'التاريخ',
        'admin.actions': 'الإجراءات',
        'admin.orderDetails': 'تفاصيل الطلب',
        'admin.address': 'العنوان',
        'admin.items': 'منتجات',
        'admin.orderItems': 'أصناف الطلب',
        'admin.quantity': 'الكمية',
        'admin.subtotal': 'المجموع الفرعي',
        'admin.shipping': 'الشحن',
        'admin.discount': 'الخصم',
        'admin.grandTotal': 'المجموع الكلي',
        'admin.paymentMethod': 'طريقة الدفع',
        'admin.paymentStatus': 'حالة الدفع',
        'admin.paymentProof': 'إثبات الدفع',
        'admin.viewLargeImage': 'عرض الصورة بالحجم الكامل',
        'admin.orderNotes': 'ملاحظات الطلب',
        'admin.trackingNumber': 'رقم التتبع',
        'admin.cash_on_delivery': 'الدفع عند الاستلام',
        'admin.instapay': 'إنستا باي (InstaPay)',
        'admin.vodafone': 'فودافون كاش',
        'admin.paid': 'تم الدفع',
        'admin.failed': 'فشل الدفع',
        'admin.refunded': 'تم الاسترداد',
        'admin.viewDetails': 'عرض التفاصيل',
        'admin.confirmOrder': 'تأكيد الطلب',
        'admin.markShipped': 'تحديد كمشحون',
        'admin.markDelivered': 'تحديد كمستلم',
        'admin.invoice': 'الفاتورة',
        'admin.statusUpdated': 'تم تحديث الحالة بنجاح',
        'admin.confirmStatusChange': 'تأكيد تغيير الحالة',
        'admin.confirmStatusChangeDesc': 'هل أنت متأكد من تغيير حالة الطلب إلى {status}؟',
        'admin.additionalInfo': 'معلومات إضافية',
        'admin.noAdditionalInfo': 'لا توجد معلومات إضافية',
        'admin.invoiceLanguage': 'لغة الفاتورة',
        'admin.errorUpdatingStatus': 'حدث خطأ في تحديث الحالة',

        // Reviews Management
        'admin.reviews': 'التقييمات',
        'admin.reviewsDesc': 'متابعة تعليقات العملاء وتقييمات المنتجات',
        'admin.searchReviews': 'البحث في التقييمات...',
        'admin.approved': 'مقبول',
        'admin.hidden': 'مخفي',
        'admin.hideReview': 'إخفاء التقييم',
        'admin.approveReview': 'قبول التقييم',
        'admin.deleteReview': 'حذف التقييم',
        'admin.confirmDeleteReview': 'سيتم حذف تقييم العميل نهائياً. هل أنت متأكد؟',
        'admin.allStatus': 'جميع الحالات',
        'admin.allTypes': 'جميع الأنواع',

        // Dashboard Stats & Info
        'admin.totalRevenue': 'إجمالي الإيرادات',
        'admin.totalSales': 'إجمالي المبيعات',
        'admin.totalCustomers': 'إجمالي العملاء',
        'admin.globalViews': 'إحصائيات المشاهدات',
        'admin.customerBase': 'قائمة العملاء',
        'admin.recentOrders': 'أحدث الطلبات',
        'admin.systemOperational': 'النظام يعمل بنجاح',
        'admin.welcomeAdmin': 'أهلاً بك، المدير',
        'admin.dashboardDesc': 'إليك نظرة سريعة على أداء متجر رداء اليوم. كل شيء يبدو رائعاً!',
        'admin.coreOperations': 'العمليات الأساسية',
        'admin.inventoryManagement': 'إدارة المخزن',
        'admin.inventoryDesc': 'إضافة أو تحديث المنتجات الفاخرة',
        'admin.orderProcessing': 'معالجة الطلبات',
        'admin.orderDesc': 'مراجعة وشحن طلبات العملاء',
        'admin.marketplaceTrends': 'اتجاهات المتجر',
        'admin.trendsDesc': 'إحصائيات كاملة للمبيعات والزيارات',
        'admin.promoEngine': 'محرك العروض',
        'admin.promoDesc': 'إنشاء وإدارة الكوبونات',
        'admin.goToModule': 'انتقال للقسم',
        'admin.globalSettings': 'الإعدادات العامة',
        'admin.interfaceLocalization': 'الواجهة واللغات',
        'admin.marketingCommunications': 'التواصل والتسويق',
        'admin.systemSecurity': 'أمان النظام',
        'admin.activeTask': 'المهمة النشطة',
        'admin.migrationStatus': 'اكتملت عملية النقل بنجاح. كافة الوحدات جاهزة.',
        'admin.marketingHub': 'الحملات التسويقية',
        'admin.marketingHubDesc': 'إرسال العروض والتحديثات للمشتركين',
        'admin.activeAudience': 'الجمهور النشط',
        'admin.subscribers': 'مشترك',
        'admin.campaignSubject': 'عنوان الحملة',
        'admin.campaignSubjectPlaceholder': 'مثال: عطلة نهاية الأسبوع - خصومات تصل إلى 50٪!',
        'admin.messageContent': 'محتوى الرسالة (يدعم HTML)',
        'admin.messagePlaceholder': 'اكتب محتوى البريد الإلكتروني هنا... استخدم <b> للنص العريض و <br/> للسطر الجديد',
        'admin.visualAsset': 'الأصل البصري',
        'admin.bannerImage': 'صورة البنر',
        'admin.recommendBannerSize': 'الموصى به: 1200x630 بكسل JPG/PNG',
        'admin.sendTestEmail': 'إرسال بريد تجريبي',
        'admin.launchCampaign': 'إطلاق الحملة',
        'admin.processing': 'جاري المعالجة...',
        'admin.imageUploaded': 'تم رفع الصورة بنجاح',

        // Coupons & Other Modules
        'admin.coupons': 'الكوبونات',
        'admin.manageCouponsDesc': 'إدارة كوبونات الخصم والرموز الترويجية',
        'admin.newCoupon': 'كوبون جديد',
        'admin.searchCouponsPlaceholder': 'ابحث عن كود الكوبون...',
        'admin.internalNameCode': 'الاسم الداخلي / الكود',
        'admin.discountDetails': 'تفاصيل الخصم',
        'admin.usageInfo': 'معلومات الاستخدام',
        'admin.expiry': 'تاريخ الانتهاء',
        'admin.autoGenerated': 'توليد تلقائي',
        'admin.never': 'غير محدد',
        'admin.percentageOff': 'خصم %',
        'admin.fixedOff': 'جنيه خصم',
        'admin.minOrder': 'أقل قيمة للطلب',
        'admin.deleteCoupon': 'حذف الكوبون',
        'admin.confirmDeleteCoupon': 'هل أنت متأكد من حذف هذا الكوبون؟',
        'admin.primarySettings': 'الإعدادات الأساسية',
        'admin.couponCodeDesc': 'سيقوم العملاء بإدخال هذا الكود عند الدفع',
        'admin.usageRules': 'شروط الاستخدام',
        'admin.minimumSpend': 'الحد الأدنى للطلبات',
        'admin.usageLimitPlaceholder': 'غير محدود',
        'admin.availability': 'التوفر والجدولة',
        'admin.publishImmediately': 'نشر فوراً',
        'admin.couponCreated': 'تم إنشاء الكوبون بنجاح',
        'admin.couponUpdated': 'تم تحديث الكوبون بنجاح',
        'admin.fillFields': 'يرجى ملء كافة الحقول المطلوبة',
        'admin.updating': 'جاري التحديث...',
        'admin.editingCouponCode': 'تعديل كود الكوبون',
        'admin.couponActive': 'الكوبون نشط',
        'admin.descriptionAr': 'الوصف (بالعربية)',
        'admin.descriptionEn': 'الوصف (بالإنجليزية)',
        'admin.timing': 'الجدولة الزمنية',
        'admin.advertisements': 'الإعلانات',
        'admin.manageAds': 'إدارة البنرات والعروض المميزة',
        'admin.newAd': 'إعلان جديد',
        'admin.editAd': 'تعديل الإعلان',
        'admin.addAd': 'إضافة إعلان',
        'admin.publishAd': 'نشر الإعلان',
        'admin.deleteAd': 'حذف الإعلان',
        'admin.confirmDeleteAd': 'هل أنت متأكد من حذف هذا الإعلان؟',
        'admin.displayMode': 'نمط العرض',
        'admin.singleHero': 'بنر رئيسي فردي',
        'admin.gridGallery': 'شبكة معرض',
        'admin.carouselSlider': 'سلايدر متحرك',
        'admin.priceOptional': 'السعر (اختياري)',
        'admin.bannerMedia': 'وسائط الإعلان',
        'admin.recommendImageSize': 'يرجى رفع صورة عالية الجودة بتنسيق JPG أو PNG. المقاس الموصى به: 1920x1080 بكسل.',
        'admin.chooseFile': 'اختر ملفاً',
        'admin.mainDetailsEn': 'التفاصيل الرئيسية (In English)',
        'admin.mainDetailsAr': 'التفاصيل الأساسية (بالعربية)',
        'admin.adTitle': 'عنوان الإعلان',
        'admin.adDescription': 'وصف الإعلان',
        'admin.subtitle': 'العنوان الفرعي',
        'admin.badge': 'شارة الإعلان',
        'admin.badgeColor': 'لون الشارة',
        'admin.highlightedWord': 'الكلمة المميزة',
        'admin.highlightedWordColor': 'لون الكلمة المميزة',
        'admin.highlightedWordUnderline': 'خط تحت الكلمة',
        'admin.addFeature': 'إضافة ميزة',
        'admin.features': 'المميزات',
        'admin.testimonialText': 'نص التوصية',
        'admin.testimonialAuthor': 'صاحب التوصية',
        'admin.promotionalBadges': 'شارات ترويجية',
        'admin.buttons': 'الأزرار الإضافية',
        'admin.href': 'الرابط',
        'admin.variant': 'نوع الزر',
        'admin.primary': 'أساسي',
        'admin.secondary': 'ثانوي',
        'admin.outline': 'إطار فقط',
        'admin.posTopRight': 'أعلى اليمين',
        'admin.posTopLeft': 'أعلى اليسار',
        'admin.posBottomRight': 'أسفل اليمين',
        'admin.posBottomLeft': 'أسفل اليسار',
        'admin.showDiscountBadge': 'إظهار شارة الخصم',
        'admin.discountBadgePosition': 'موقع شارة الخصم',
        'admin.sendOffers': 'إرسال العروض',
        'admin.analytics': 'الإحصائيات',
        'admin.analyticsDesc': 'عرض إحصائيات المتجر وأداء المبيعات',
        'admin.topProducts': 'المنتجات الأكثر مبيعاً',
        'admin.unknownUser': 'مستخدم مجهول',
        'admin.recentActivity': 'النشاط الأخير',
        'admin.users': 'إدارة المستخدمين',
        'admin.manageUsers': 'إدارة المستخدمين',
        'admin.manageUsersDesc': 'إدارة وتتبع جميع المستخدمين المسجلين',
        'admin.userDetails': 'تفاصيل المستخدم',
        'admin.personalInfo': 'المعلومات الشخصية',
        'admin.subscription': 'الاشتراك',
        'admin.deactivateAccount': 'تعطيل الحساب',
        'admin.activateAccount': 'تفعيل الحساب',
        'admin.confirmDeleteUser': 'هل أنت متأكد من حذف هذا المستخدم؟',
        'admin.userDeleted': 'تم حذف المستخدم بنجاح',
        'admin.errorUpdatingUser': 'فشل تحديث حالة المستخدم',
        'admin.loadingUsers': 'جاري تحميل قائمة المستخدمين...',
        'admin.noDataExport': 'لا توجد بيانات للتصدير',
        'admin.usersReport': 'تقرير المستخدمين',
        'admin.subscribed': 'مشترك',
        'admin.notSubscribed': 'غير مشترك',
        'admin.statusAll': 'الحالة: الكل',
        'admin.verifAll': 'التحقق: الكل',
        'admin.newsAll': 'النشرة: الكل',
        'admin.firstName': 'الاسم الأول',
        'admin.lastName': 'الاسم الأخير',
        'admin.email': 'البريد الإلكتروني',
        'admin.phone': 'رقم الهاتف',
        'admin.verified': 'متحقق',
        'admin.unverified': 'غير متحقق',
        'admin.newsletter': 'النشرة',
        'admin.lastLogin': 'آخر دخول',
        'admin.total': 'الإجمالي',
        'admin.searchUsers': 'البحث عن مستخدم...',
        'admin.default': 'افتراضي',
        'admin.settings': 'الإعدادات',
        'admin.settingsDesc': 'إدارة إعدادات المتجر العامة والتفضيلات',
        'admin.controlPanel': 'لوحة التحكم',
        'admin.adminProfile': 'الملف الشخصي للمشرف',
        'admin.storeCore': 'إعدادات المتجر الأساسية',
        'admin.seoAnalytics': 'تحسين محركات البحث والإحصائيات',
        'admin.adminIdentity': 'هوية المسؤول',
        'admin.adminIdentityDesc': 'إدارة بيانات اعتماد الإدارة ومعلومات الاتصال',
        'admin.updateProfile': 'تحديث الملف الشخصي',
        'admin.fullLegalName': 'الاسم القانوني الكامل',
        'admin.authorizedEmail': 'البريد الإلكتروني المعتمد',
        'admin.loginUsername': 'اسم مستخدم تسجيل الدخول',
        'admin.adminHotline': 'رقم الطوارئ للإدارة',
        'admin.changePassword': 'تغيير كلمة المرور',
        'admin.oldPassword': 'كلمة المرور الحالية',
        'admin.newPassword': 'كلمة المرور الجديدة',
        'admin.confirmPassword': 'تأكيد كلمة المرور الجديدة',
        'admin.updatePassword': 'تحديث كلمة المرور',
        'admin.passwordChanged': 'تم تغيير كلمة المرور بنجاح',
        'admin.passwordError': 'حدث خطأ في تغيير كلمة المرور',
        'admin.passwordsDontMatch': 'كلمات المرور غير متطابقة',
        'admin.allFieldsRequired': 'يرجى ملء كافة الحقول المطلوبة',
        'admin.heroSection': 'قسم البداية (Hero)',
        'admin.heroTitleAr': 'العنوان الرئيسي بالعربية',
        'admin.heroTitleEn': 'العنوان الرئيسي بالإنجليزية',
        'admin.heroSubtitleAr': 'العنوان الفرعي بالعربية',
        'admin.heroSubtitleEn': 'العنوان الفرعي بالإنجليزية',
        'admin.storySection': 'قصتنا',
        'admin.storyTitleAr': 'عنوان القصة بالعربية',
        'admin.storyTitleEn': 'عنوان القصة بالإنجليزية',
        'admin.storyImageTextAr': 'نص الصورة بالعربية',
        'admin.storyImageTextEn': 'نص الصورة بالإنجليزية',
        'admin.storyImageSubtextAr': 'النص الفرعي للصورة بالعربية',
        'admin.storyImageSubtextEn': 'النص الفرعي للصورة بالإنجليزية',
        'admin.missionAndVision': 'الرؤية والمهمة',
        'admin.missionTitleAr': 'عنوان المهمة بالعربية',
        'admin.missionTitleEn': 'عنوان المهمة بالإنجليزية',
        'admin.missionContentAr': 'محتوى المهمة بالعربية',
        'admin.missionContentEn': 'محتوى المهمة بالإنجليزية',
        'admin.visionTitleAr': 'عنوان الرؤية بالعربية',
        'admin.visionTitleEn': 'عنوان الرؤية بالإنجليزية',
        'admin.visionContentAr': 'محتوى الرؤية بالعربية',
        'admin.visionContentEn': 'محتوى الرؤية بالإنجليزية',
        'admin.featuresSection': 'المميزات',
        'admin.featuresTitleAr': 'عنوان المميزات بالعربية',
        'admin.featuresTitleEn': 'عنوان المميزات بالإنجليزية',
        'admin.feature': 'ميزة',
        'admin.ctaSection': 'دعوة لاتخاذ إجراء (CTA)',
        'admin.ctaTitleAr': 'عنوان الـ CTA بالعربية',
        'admin.ctaTitleEn': 'عنوان الـ CTA بالإنجليزية',
        'admin.ctaDescriptionAr': 'وصف الـ CTA بالعربية',
        'admin.ctaDescriptionEn': 'وصف الـ CTA بالإنجليزية',
        'admin.ctaButton1TextAr': 'نص الزر الأول بالعربية',
        'admin.ctaButton1TextEn': 'نص الزر الأول بالإنجليزية',
        'admin.addressAr': 'العنوان بالعربية',
        'admin.addressEn': 'العنوان بالإنجليزية',
        'admin.brandParameters': 'ثوابت العلامة التجارية',
        'admin.brandParametersDesc': 'تكوين تفاصيل المتجر العالمية ونقاط الاتصال',
        'admin.nomenclature': 'تسميات المتجر',
        'admin.arabicStoreName': 'اسم المتجر بالعربية',
        'admin.englishStoreName': 'اسم المتجر بالإنجليزية',
        'admin.financials': 'الإعدادات المالية',
        'admin.defaultShippingFee': 'رسوم الشحن الافتراضية',
        'admin.showHomepageAds': 'عرض إعلانات الصفحة الرئيسية',
        'admin.publicPhone': 'رقم الهاتف العام',
        'admin.whatsAppLine': 'خط الواتساب',
        'admin.publicEmail': 'البريد الإلكتروني العام',
        'admin.currency': 'العملة',
        'admin.timezone': 'المنطقة الزمنية',
        'admin.instaPayNumber': 'رقم إنستا باي (InstaPay)',
        'admin.instaPayAccountName': 'اسم صاحب حساب إنستا باي',
        'admin.vodafoneNumber': 'رقم فودافون كاش',
        'admin.socialAndAnnouncement': 'التواصل والبنر الإعلاني',
        'admin.socialMedia': 'روابط التواصل الاجتماعي',
        'admin.announcementBar': 'شريط الإعلانات العلوي',
        'admin.enabled': 'مفعل',
        'admin.disabled': 'معطل',
        'admin.speed': 'السرعة',
        'admin.messagesAr': 'الرسائل بالعربية (رسالة في كل سطر)',
        'admin.messagesEn': 'الرسائل بالإنجليزية (رسالة في كل سطر)',
        'admin.pagesContent': 'محتوى الصفحات الثابتة',
        'admin.contactPage': 'صفحة اتصل بنا',
        'admin.aboutPage': 'صفحة من نحن',
        'admin.termsPage': 'الشروط والخصوصية',
        'admin.searchPresence': 'ظهور المتجر في البحث',
        'admin.searchPresenceDesc': 'التحكم في كيفية ظهور متجرك على جوجل ومنصات التواصل الاجتماعي',
        'admin.saveMetadata': 'حفظ البيانات الوصفية',
        'admin.globalKeywords': 'الكلمات المفتاحية العامة (مفصولة بفاصلة)',
        'admin.arabicMetaDescription': 'وصف الميتا بالعربية',
        'admin.englishMetaDescription': 'وصف الميتا بالإنجليزية',
        'admin.systemAlerts': 'تنبيهات النظام',
        'admin.systemAlertsDesc': 'تكوين التنبيهات الآلية لمختلف الأحداث',
        'admin.saveRules': 'حفظ القواعد',
        'admin.emailNotificationsLabel': 'تنبيهات البريد الإلكتروني العامة',
        'admin.allowEmailsDesc': 'السماح للنظام بإرسال رسائل البريد الإلكتروني لأي سبب',
        'admin.newOrderAlertsLabel': 'تنبيهات الطلبات الجديدة',
        'admin.newOrderAlertsDesc': 'احصل على تنبيه فوري عند تقديم طلب جديد',
        'admin.lowStockWarningsLabel': 'تحذيرات انخفاض المخزون',
        'admin.lowStockWarningsDesc': 'تنبيه عندما ينخفض مخزون المنتج عن الحد الأدنى',
        'admin.dailyReportsLabel': 'تقارير الملخص اليومي',
        'admin.dailyReportsDesc': 'تلقي ملخص أداء يومي عبر البريد الإلكتروني',
        'admin.analyticsSummary': 'لقد نمت أرباحك بنسبة {revenueGrowth}% مقارنة بالفترة السابقة. ركز على تحسين تجربة الجوال حيث أن {mobilePercent}% من زياراتك تأتي من الجوال.',
        'admin.crunchingNumbers': 'جاري تحليل الأرقام والبيانات...',
        'admin.monitorPerformance': 'مراقبة أداء مبيعاتك ونمو متجرك',
        'admin.today': 'اليوم',
        'admin.last7Days': 'آخر 7 أيام',
        'admin.last30Days': 'آخر 30 يوم',
        'admin.lastQuarter': 'الربع الأخير',
        'admin.revenueTrend': 'اتجاه الإيرادات',
        'admin.ordersTrend': 'اتجاه الطلبات',
        'admin.topPerformingProducts': 'المنتجات الأكثر مبيعاً',
        'admin.conversionFunnel': 'تفاعل الأجهزة',
        'admin.mobileUsers': 'مستخدمو الجوال',
        'admin.desktopUsers': 'مستخدمو الكمبيوتر',
        'admin.tabletUsers': 'مستخدمو التابلت',
        'admin.growthSummary': 'ملخص النمو',
        'admin.converRate': 'معدل التحويل',
        'admin.dashboardSubtitle': 'لوحة التحكم للمسؤولين',
        'admin.systemAdmin': 'مدير النظام',
        'admin.loginTitle': 'لوحة تحكم رِداء - Ridaa Admin',
        'admin.allRightsReserved': 'جميع الحقوق محفوظة',
        'admin.invalidCredentials': 'اسم المستخدم أو كلمة المرور غير صحيحة',
        'admin.loginButton': 'تسجيل الدخول',

        // System & Units
        'admin.unit.egp': 'جنيه مصري',
        'admin.unit.orders': 'طلبات',
        'admin.unit.visits': 'زيارات',
        'admin.unit.users': 'عملاء',
        'admin.verifyingPermissions': 'جاري التحقق من الصلاحيات...',
        'admin.accessDenied': 'غير مصرح لك بالوصول',
        'admin.redirecting': 'جاري إعادة التوجيه...',
        'admin.csrfTokenMissing': 'انتهت صلاحية الجلسة. يرجى تسجيل الدخول مرة أخرى.',
        'admin.sections': 'هيكلة المتجر (الأقسام)',
        'admin.storeArchitecture': 'هيكلة المتجر',
        'admin.storeArchitectureDesc': 'إدارة ترتيب وأقسام الصفحة الرئيسية والموقع',
        'admin.saveStructure': 'حفظ الهيكلة',
        'admin.capacity': 'السعة',
        'admin.block': 'قسم',
        'admin.displayLabels': 'تسميات العرض',
        'admin.visibilityRules': 'قواعد الظهور',
        'admin.titleVisible': 'العنوان ظاهر',
        'admin.titleHidden': 'العنوان مخفي',
        'admin.ctaVisible': 'زر الانتقال ظاهر',
        'admin.ctaHidden': 'زر الانتقال مخفي',
        'admin.manualSelection': 'اختيار يدوي للمنتجات',
        'admin.autoSelection': 'تلقائي (الأحدث)',
        'admin.aboutHero': 'واجهة صفحة من نحن',
        'admin.aboutStory': 'قصتنا وتفاصيلنا',
        'admin.aboutVision': 'الرؤية والمهمة',
        'admin.aboutFeatures': 'المميزات والخصائص',
        'admin.aboutCTA': 'الدعوة للعمل (CTA)',
        'admin.selectedProducts': 'منتجات مختارة',
        'admin.clearAll': 'مسح الكل',
        'admin.searchPlaceholder': 'ابحث بالاسم أو الكود...',
        'admin.saving': 'جاري الحفظ...',
        'admin.heroTitle': 'عنوان الواجهة',
        'admin.heroDescription': 'وصف الواجهة',
        'admin.lastUpdated': 'آخر تحديث',
        'admin.sectionSubtitle': 'عنوان القسم الفرعي',
        'admin.sectionText': 'نص القسم',
        'admin.addSection': 'إضافة قسم جديد',
        'admin.noticeTitle': 'عنوان التنبيه الهام',
        'admin.noticeText': 'نص التنبيه الهام',
        'admin.pageEnabled': 'الصفحة مفعلة',
        'admin.pageDisabled': 'الصفحة معطلة',
    },
    en: {
        'common.loading': 'Loading...',
        'admin.parentCategory': 'Parent Category',
        'admin.categoryImage': 'Category Image',
        'admin.none': 'None',
        'admin.categoryName': 'Category Name',
        'admin.activeCategory': 'Active Category',
        'admin.descriptionAr': 'Description (AR)',
        'admin.descriptionEn': 'Description (EN)',
        'admin.instaPayNumber': 'InstaPay Number',
        'admin.instaPayAccountName': 'InstaPay Account Name',
        'admin.vodafoneNumber': 'Vodafone Cash Number',
        'admin.socialAndAnnouncement': 'Social & Announcement',
        'admin.socialMedia': 'Social Media Links',
        'admin.announcementBar': 'Announcement Bar',
        'admin.enabled': 'Enabled',
        'admin.disabled': 'Disabled',
        'admin.speed': 'Speed',
        'admin.messagesAr': 'Arabic Messages',
        'admin.messagesEn': 'English Messages',
        'admin.pagesContent': 'Static Pages Content',
        'admin.contactPage': 'Contact Page',
        'admin.aboutPage': 'About Page',
        'admin.termsPage': 'Terms & Privacy',
        'admin.manageOrders': 'Manage Orders',
        'admin.manageOrdersDesc': 'View and manage customer orders',
        'admin.searchOrders': 'Search orders...',
        'admin.total': 'Total',
        'admin.pending': 'Pending',
        'admin.confirmed': 'Confirmed',
        'admin.shipped': 'Shipped',
        'admin.outForDelivery': 'Out for Delivery',
        'admin.delivered': 'Delivered',
        'admin.cancelled': 'Cancelled',
        'admin.order': 'Order',
        'admin.customer': 'Customer',
        'admin.status': 'Status',
        'admin.date': 'Date',
        'admin.actions': 'Actions',
        'admin.orderDetails': 'Order Details',
        'admin.address': 'Address',
        'admin.items': 'Items',
        'admin.orderItems': 'Order Items',
        'admin.quantity': 'Quantity',
        'admin.subtotal': 'Subtotal',
        'admin.shipping': 'Shipping',
        'admin.discount': 'Discount',
        'admin.grandTotal': 'Grand Total',
        'admin.paymentMethod': 'Payment Method',
        'admin.paymentStatus': 'Payment Status',
        'admin.paymentProof': 'Payment Proof',
        'admin.viewLargeImage': 'View Full Image',
        'admin.orderNotes': 'Order Notes',
        'admin.trackingNumber': 'Tracking Number',
        'admin.cash_on_delivery': 'Cash on Delivery',
        'admin.instapay': 'InstaPay',
        'admin.vodafone': 'Vodafone Cash',
        'admin.paid': 'Paid',
        'admin.failed': 'Failed',
        'admin.refunded': 'Refunded',
        'admin.viewDetails': 'View Details',
        'admin.confirmOrder': 'Confirm Order',
        'admin.cancel': 'Cancel',
        'admin.markShipped': 'Mark Shipped',
        'admin.markDelivered': 'Mark Delivered',
        'admin.invoice': 'Invoice',
        'admin.statusUpdated': 'Status updated successfully',
        'admin.confirmStatusChange': 'Confirm Status Change',
        'admin.confirmStatusChangeDesc': 'Are you sure you want to change order status to {status}?',
        'admin.additionalInfo': 'Additional Information',
        'admin.noAdditionalInfo': 'No additional information',
        'admin.refreshData': 'Refresh Data',
        'admin.unit.egp': 'EGP',
        'admin.changePassword': 'Change Password',
        'admin.oldPassword': 'Current Password',
        'admin.newPassword': 'New Password',
        'admin.confirmPassword': 'Confirm New Password',
        'admin.updatePassword': 'Update Password',
        'admin.basicInfo': 'Basic Information',
        'admin.media': 'Media & Images',
        'admin.variants': 'Variants & Stock',
        'admin.seoAndTags': 'SEO & Tags',
        'admin.termsAndPrivacy': 'Terms & Privacy',
        'admin.privacyPolicy': 'Privacy Policy',
        'admin.termsAndConditions': 'Terms & Conditions',
        'admin.metaTitleEn': 'Meta Title (English)',
        'admin.metaTitleAr': 'Meta Title (Arabic)',
        'admin.metaDescriptionEn': 'Meta Description (English)',
        'admin.metaDescriptionAr': 'Meta Description (Arabic)',
        'admin.shortDescriptionAr': 'Short Description (Arabic)',
        'admin.shortDescriptionEn': 'Short Description (English)',
        'admin.allFieldsRequired': 'All fields are required',
        'admin.heroSection': 'Hero Section',
        'admin.storySection': 'Story Section',
        'admin.missionAndVision': 'Mission & Vision',
        'admin.featuresSection': 'Features Section',
        'admin.ctaSection': 'CTA Section',
        'admin.feature': 'Feature',
        'admin.addressAr': 'Address (Arabic)',
        'admin.addressEn': 'Address (English)',
        'admin.sections': 'Store Architecture',
        'admin.storeArchitecture': 'Store Architecture',
        'admin.storeArchitectureDesc': 'Manage the layout and order of homepage sections.',
        'admin.saveStructure': 'Save Structure',
        'admin.capacity': 'Capacity',
        'admin.block': 'Block',
        'admin.displayLabels': 'Display Labels',
        'admin.visibilityRules': 'Visibility Rules',
        'admin.titleVisible': 'Title Visible',
        'admin.titleHidden': 'Title Hidden',
        'admin.ctaVisible': 'CTA Visible',
        'admin.ctaHidden': 'CTA Hidden',
        'admin.manualSelection': 'Manual Selection',
        'admin.autoSelection': 'Automatic',
        'admin.aboutHero': 'About Hero',
        'admin.aboutStory': 'Our Story',
        'admin.aboutVision': 'Mission & Vision',
        'admin.aboutFeatures': 'Features',
        'admin.aboutCTA': 'Call to Action',
        'admin.selectedProducts': 'Selected',
        'admin.clearAll': 'Clear All',
        'admin.searchPlaceholder': 'Search by name or SKU...',
        'admin.saving': 'Saving...',
        'admin.heroTitle': 'Hero Title',
        'admin.heroDescription': 'Hero Description',
        'admin.lastUpdated': 'Last Updated',
        'admin.sectionSubtitle': 'Section Subtitle',
        'admin.sectionText': 'Section Text',
        'admin.addSection': 'Add Section',
        'admin.noticeTitle': 'Notice Title',
        'admin.noticeText': 'Notice Text',
        'admin.pageEnabled': 'Page Enabled',
        'admin.pageDisabled': 'Page Disabled',
        'admin.autoGenerated': 'Auto Generated',
    },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('ar');
    const [supportedLanguages] = useState([
        { language: 'ar', name: 'العربية' },
    ]);
    const [isTranslating] = useState(false);
    const [translationError] = useState<string | null>(null);

    const isMounted = React.useRef(false);

    useEffect(() => {
        if (!isMounted.current) {
            document.documentElement.lang = 'ar';
            document.documentElement.dir = 'rtl';
            localStorage.setItem('language', 'ar');
            isMounted.current = true;
        }
    }, []);

    const t = React.useCallback((key: string): string => {
        const langTranslations = translations[language];
        if (langTranslations && key in langTranslations) {
            return langTranslations[key];
        }
        return key.replace(/^(admin|common|products|order|header|footer)\./, '');
    }, [language]);

    const translateTextAsync = React.useCallback(async (text: string): Promise<string> => text, []);
    const getSupportedLanguages = React.useCallback(async () => { }, []);

    const value = React.useMemo<LanguageContextType>(() => ({
        language,
        setLanguage,
        t,
        isRTL: true,
        translateText: translateTextAsync,
        isTranslating,
        translationError,
        supportedLanguages,
        getSupportedLanguages
    }), [language, t, translateTextAsync, isTranslating, translationError, supportedLanguages, getSupportedLanguages]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
